/*
================================================================================
================================================================================
==  
==  WARNING: THIS FILE IS CURRENTLY INACTIVE (QUARANTINED)
==  
==  The logic for the MigrationPanel is currently implemented *directly* inside
==  the App.jsx file as part of the "Monolith Maneuver".
==
==  DO NOT EDIT THIS FILE. Your changes will NOT be reflected in the application.
==
==  This file is being preserved as a clean blueprint for the future
==  "Operation: Refactor", at which point the logic will be moved back here.
==
================================================================================
================================================================================
*/

import React from 'react';
import { renderMigrationForm } from './migrationFormRenderer';

export const MigrationPanel = ({ AIA_UDS, stagedData, schemas, allEffects, db, clearStagedData }) => {
  if (!stagedData || stagedData.length === 0) {
    return (
      <div className="bg-gray-800 rounded-lg shadow-xl p-6 border border-amber-500/50">
        <h2 className="text-2xl font-semibold text-amber-300 mb-4 text-center">Migration Workshop</h2>
        <div className="text-center text-gray-400 py-8">
          <p>Run the Deconstructor in The Forge to begin the automated deconstruction pipeline.</p>
          <p>Proposed objects will appear here for verification.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-gray-800 rounded-lg shadow-xl p-6 border border-amber-500/50">
      <h2 className="text-2xl font-semibold text-amber-300 mb-4 text-center">Migration Workshop</h2>
      <div className="max-h-[70vh] overflow-y-auto pr-2 space-y-8">
        {stagedData.map((item, itemIndex) => (
          <div key={itemIndex} id={`staged-item-${itemIndex}`} className="bg-gray-900/50 p-4 rounded-lg border border-gray-700">
            <h3 className="text-2xl font-semibold text-amber-400 mb-4">
              Staged Item {itemIndex + 1}: {item.ability_to_create?.name || 'Untitled'}
            </h3>
            
            {item.effects_to_create && item.effects_to_create.length > 0 && (
              <>
                <h4 className="text-lg font-semibold text-sky-300 mb-2 border-b border-sky-500/50 pb-1">Proposed Effects</h4>
                <div className="space-y-4">
                  {item.effects_to_create.map((effect, effectIndex) => (
                    <div key={effectIndex}>
                      {renderMigrationForm(schemas, 'effects', `item-${itemIndex}-effect-${effectIndex}`, effect, [], allEffects)}
                    </div>
                  ))}
                </div>
              </>
            )}

            {item.ability_to_create && (
               <>
                <h4 className="text-lg font-semibold text-emerald-300 mt-6 mb-2 border-b border-emerald-500/50 pb-1">Proposed Ability</h4>
                 {renderMigrationForm(schemas, 'abilities', `item-${itemIndex}-ability-0`, item.ability_to_create, item.effects_to_create, allEffects)}
               </>
            )}
          </div>
        ))}
      </div>

      <div className="flex justify-end space-x-4 mt-8">
        <button
          onClick={() => {}} // Placeholder for now
          className="bg-emerald-600 hover:bg-emerald-700 disabled:bg-emerald-800/50 disabled:cursor-not-allowed text-white font-bold py-3 px-6 rounded-lg text-lg transition"
          disabled={!stagedData || stagedData.length === 0}
        >
          Approve & Commit All ({stagedData?.length || 0})
        </button>
        <button
          onClick={() => {}} // Placeholder for now
          className="bg-gray-600 hover:bg-gray-700 disabled:bg-gray-800/50 disabled:cursor-not-allowed text-white font-bold py-3 px-6 rounded-lg text-lg transition"
          disabled={!stagedData || stagedData.length === 0}
        >
          Reject and Clear All ({stagedData?.length || 0})
        </button>
      </div>
    </div>
  );
};

